<?xml version="1.0" encoding="UTF-8"?><testrun name="HighscoreListTest.testListListenerMoreThanMax" project="Oving8" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testcase name="testListListenerMoreThanMax" classname="patterns.observable.HighscoreListTest" time="0.0">
    <failure>junit.framework.AssertionFailedError: addResult(3, 1) failed: expected:&lt;1&gt; but was:&lt;3&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:47)&#13;
	at patterns.observable.HighscoreListTest._transition_exprAction__listListenerMoreThanMax_transitions1_actions0(HighscoreListTest.java:558)&#13;
	at patterns.observable.HighscoreListTest.testListListenerMoreThanMax(HighscoreListTest.java:119)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:164)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:130)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:106)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&#13;
	at junit.framework.TestResult.run(TestResult.java:109)&#13;
	at junit.framework.TestCase.run(TestCase.java:120)&#13;
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:131)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
  </testcase>
</testrun>
